### ISSUE TITLE
Static table for access-control-request-headers (index 80)

### ISSUE THREAD

**Issue by tcfw** [marten-seemann/qpack#19]
Found an issue when trying to use CORS via HTTP3 (lucas-clemente/quic-go) that the "allow-control-request-headers" was being interpreted as the "allow-control-expose-headers" when the request was coming from chrome 86.0.4240.111 and firefox 82.0.

I've checked the most recent draft-ietf-quic-qpack-19 and found in the static table that it should be coming in as index 80 but looking here it's paired with index 79.

**Comment by marten-seemann** [comment]
You mean that this line is incorrect, right?
https://github.com/marten-seemann/qpack/blob/f1218f693233709a863ecf6097f6aa639f58d200/static_table.go#L84

Would you mind sending us a PR to fix it (both in this line and in the `encoderMap` table)?

**Comment by tcfw** [comment]
That's the one, I believe. 

Will send through shortly.
