### ISSUE TITLE
goroutine 1 [running]: github.com/marten-seemann/qtls-go1-15.init.0()         /Users/zxj/go/pkg/mod/github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x12c  Process finished with the exit code 2

### ISSUE THREAD

**Issue by zhuxiujia** [marten-seemann/qpack#27]
goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
        /Users/zxj/go/pkg/mod/github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x12c

Process finished with the exit code 2

**Comment by zhuxiujia** [comment]
Have you tested the latest version of GO? It is recommended to add compile tests on Github and Action

**Comment by marten-seemann** [comment]
Wrong repo? This is qpack here, not qtls.
